app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('logout_user', views.logout_user, name='logout'),
    path('register_user', views.user_register, name='register'),
    path('index/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('event/', views.event, name='event'),
    path('program/', views.program, name='program'),
    path('service/', views.service, name='service'),
    path('team/', views.team, name='team'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('index2/', views.index2, name="index2"),
    path('appointments/', views.create_appointment, name='create_appointment'),
    path('appointment_lists/', views.get_appointments, name='get_appointments'),
    path('appointments/<int:appointment_id>/', views.update_appointment, name='update_appointment'),
    path('appointments/<int:appointment_id>/', views.delete_appointment, name='delete_appointment'),
    path('emp', views.emp, name='emp'),
    path('show', views.show, name='show'),
    path('edit/<int:id>', views.edit, name='edit'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('register/', include("django.contrib.auth.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/authenticate/login.html
{% extends 'authenticate/base2.html' %}
{% load static %}
{% block body %}
    <h1>Login</h1>
    <form action="" method="post">
    {% csrf_token %}

    <div class="mb-2 p-5">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3 p-5" >
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" name="password">
    </div>
    <input type="submit" value="Submit" class="btn btn-secondary mb-4 ">
    </form>

{% endblock %}

app/templates/authenticate/user_register.html
{% extends 'authenticate/base2.html' %}
{% load static %}
{% block body %}
    {% if form.errors %}

    <div class="container">
        {% if messages %}
            {% for message in messages %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <strong>There was an error with your form</strong> You should check in on some of those fields below.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    </div>


    {% endif %}
    <div class="showdow p-5 mb-5 bg-body rounded">
    <h1>Register</h1>
    <form action="{% url 'app:register' %}" method="post">
    {% csrf_token %}
    {{ form  }}
        <br>
    <input type="submit" value="Submit" class="btn btn-secondary mb-4 ">
    </form>
    </div>
{% endblock %}